# Generated by Django 4.2.3 on 2023-08-07 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0003_exercise_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmrequest',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='CryptText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintext', models.TextField()),
                ('ciphertext', models.TextField()),
                ('key', models.TextField()),
                ('ip_addr', models.CharField(max_length=200)),
                ('cryptreq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.vmrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CryptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(max_length=200)),
                ('random_key', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=300, null=True)),
                ('num_cipher', models.PositiveSmallIntegerField(null=True)),
                ('ip_address_list', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
