# Generated by Django 4.2.3 on 2023-08-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_vmrequest_description_crypttext_cryptrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypttext',
            name='ip_addr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
