# Generated by Django 4.2.3 on 2023-08-08 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_crypttext_ip_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypttext',
            name='cryptreq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.cryptrequest'),
        ),
    ]
