# Generated by Django 4.2.3 on 2023-08-09 16:01

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_crypttext_cryptreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='pdf_file',
            field=models.FileField(upload_to='exercises/', validators=[forms.models.validate_pdf_extension]),
        ),
    ]
