# Generated by Django 4.2.3 on 2023-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_exercise_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmrequest',
            name='cpu_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vmrequest',
            name='disk_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vmrequest',
            name='end_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vmrequest',
            name='hard_disk',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vmrequest',
            name='ram',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vmrequest',
            name='ram_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vmrequest',
            name='self_sudo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vmrequest',
            name='start_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vmrequest',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vmrequest',
            name='vm_user_file',
            field=models.FileField(null=True, upload_to='vm_users/'),
        ),
        migrations.AlterField(
            model_name='vmrequest',
            name='vm_users',
            field=models.TextField(null=True),
        ),
    ]
