# Generated by Django 4.2.3 on 2023-08-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_vmrequest_cpu_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='template',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vmrequest',
            name='course_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
