# Generated by Django 4.2.3 on 2023-08-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_vm_template_alter_vmrequest_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='folder_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vmrequest',
            name='ta_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
