---
- name: Restart VM
  hosts: localhost
  gather_facts: false
  collections:
   - community.vmware

  vars_files:
   - secret.yml


  tasks:
   - name: Read json
     set_fact:
        machine_list: "{{ machine_list|from_json}}"
        
   - name: Restart vm
     vmware_guest_powerstate:
        hostname: "{{vcenter_hostname}}"
        username: "{{vcenter_username}}"
        password: "{{vcenter_password}}"
        validate_certs: "{{vcenter_validate_certs}}"
        folder: "{{item.split(',')[0]}}"
        name: "{{item.split(',')[1]}}"
        state: restarted
     loop: "{{machine_list}}"
     loop_control:
        loop_var: item
